#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database
from cheese.Logger import Logger
from python.models.notifications import Notifications


class NotificationsRepositoryImpl:

    @staticmethod
    def init():
        NotificationsRepositoryImpl.table = "notifications"
        NotificationsRepositoryImpl.scheme = "(id,end_time,repeat,description)"
        NotificationsRepositoryImpl.schemeNoBrackets = "id,end_time,repeat,description"

    @staticmethod
    def convert(var):
        if (type(var) is int):
            var = int(var)
        elif (type(var) is float):
            var = float(var)
        return var

    @staticmethod
    def toJson(object):
        scheme = NotificationsRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

    @staticmethod
    def toModel(obj):
        model = Notifications()
        model.id = NotificationsRepositoryImpl.convert(obj[0])
        model.end_time = NotificationsRepositoryImpl.convert(obj[1])
        model.repeat = NotificationsRepositoryImpl.convert(obj[2])
        model.description = NotificationsRepositoryImpl.convert(obj[3])
        return model

    @staticmethod
    def fromModel(model):
        tuple = (
            model.id,
            model.end_time,
            model.repeat,
            model.description
        )
        return tuple

    @staticmethod
    def findPassedNotifications(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {NotificationsRepositoryImpl.schemeNoBrackets} from notifications where end_time <= now();")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(NotificationsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findAll(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {NotificationsRepositoryImpl.schemeNoBrackets} from notifications;")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(NotificationsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def find(args):
        id = args[0]

        response = None
        try:
            db = Database()
            response = db.query(f"select {NotificationsRepositoryImpl.schemeNoBrackets} from notifications where id={id};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        if (len(response) > 0):
            return NotificationsRepositoryImpl.toModel(response[0])
        else: return None

    @staticmethod
    def findBy(args):
        columnName = args[0]
        value = args[1]

        response = None
        try:
            db = Database()
            response = db.query(f"select {NotificationsRepositoryImpl.schemeNoBrackets} from notifications where {columnName}={value};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(NotificationsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findNewId(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select max(id) from {NotificationsRepositoryImpl.table};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        try: return int(response[0][0])
        except: return -1

    @staticmethod
    def save(args):
        obj = NotificationsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"insert into {NotificationsRepositoryImpl.table} {NotificationsRepositoryImpl.scheme} values {obj};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def update(args):
        obj = NotificationsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"update {NotificationsRepositoryImpl.table} set {NotificationsRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def delete(args):
        obj = NotificationsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"delete from {NotificationsRepositoryImpl.table} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

